---
name: Continuous Integration

on: push

jobs:
  test-my-actions:
    name: Hello Hello
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Sanity check
        run: echo "It is working!"

  test-my-2nd-job:
    name: Run in parallel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python --version
