---
name: Continuous Integration

on: push

jobs:
  linting:
    name: Lint using Black, flake8, Mypy and isort
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Run Black
        run: black --diff --check .

      - name: Run mypy
        run: mypy $(git ls-files '*.py')

      - name: Run isort
        run: isort --check --diff .

      - name: Run flake8
        run: flake8 --max-line-length=86


  test:
    name: Run tests in parallel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: pytest --cov-report term-missing:skip-covered --cov -vv
